version: "3.9"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "ROOTPASSWORD"
      MYSQL_DATABASE: "BRAVOServer"
      MYSQL_USER: "BRAVOAdmin"
      MYSQL_PASSWORD: "AdminPassword"
    ports:
      - '3306:3306'
    volumes:
      - SQLDatabase:/var/lib/mysql
    networks:
      - backend
  
  bravo-server:
    image: jcagle95/bravo-server:3.0.1
    restart: always
    environment:
      BRAVO_DATABASE: "BRAVOServer"
      BRAVO_DATABASE_USER: "BRAVOAdmin"
      BRAVO_DATABASE_PASSWORD: "AdminPassword"
      BRAVO_DATABASE_HOST: "mysql"
      BRAVO_DATABASE_PORT: "3306"

      REDIS_HOST: "redis"
      DATASERVER_ENCRYPTION: "O6sHoRxTt3dYohP0kndr6rvFl8ebxZbELT9wKI2FICk="
      DATASERVER_HASHKEY: "BRAVOServerHashkey="
      DJANGO_SECRET_KEY: "django-insecure-v#aagfodpaihopfda#$$%()I*()RETGEDRF*()a+"
      SERVER_ADDRESS: "http://localhost:27286"
      SERVER_HOST: "localhost"
      DJANGO_MODE: "DEBUG"

      FIBIT_CLIENT_SECRET: ""
      FIBIT_CLIENT_ID: ""
      
    stdin_open: true
    tty: true
    depends_on:
      - mysql
      - redis
    networks:
      - backend
    volumes:
      - BRAVOStorage:/usr/src/BRAVO/BRAVOStorage
    ports:
      - '80:80'
      - '443:443'
      - '27286:27286'
    command: >
      bash -c "env >> /etc/environment && service nginx start && python3 manage.py migrate && python3 manage.py runserver 0:27286"
  
  redis:
    image: redis:5
    restart: always
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:

volumes:
  SQLDatabase:
    name: sqldata
  BRAVOStorage: 