"""An ordinal Gaussian-process model of side-effect severity over stimulation parameters.

What problem this file solves
-----------------------------
Until now the safety layer of this module has been :class:`StimOptimizer.routines.surrogate
.SafetyGP`, which is a Gaussian process over a numeric severity score with a prior mean that is
forced to be non-decreasing in stimulation amplitude. That construction embeds two assumptions,
and both of them are now known to be wrong for this participant.

The first assumption is that severity is a number. It is not. The coded acute record labels each
step with one of four ordered categories: none, mild, moderate, severe. Treating those labels as
the numbers 0, 1, 2, 3 and fitting a Gaussian likelihood to them asserts that the step from
"none" to "mild" is the same size as the step from "moderate" to "severe", which nobody has
established and which nothing in the coding procedure was designed to make true. It also lets
the model predict severity values such as 1.4 or -0.3, which correspond to no clinical statement
at all, and it makes the reported uncertainty a statement about a fictitious continuous quantity
rather than about the probability of a category a clinician can act on.

The second assumption is that severity increases with amplitude. In this participant's record it
does not. That is not a modelling preference; it is what the data say, and the numbers are
re-derived from the file every time this module's analysis is run rather than quoted from
memory. A model whose prior mean is constrained to be non-decreasing in amplitude cannot report
that finding, because it has assumed the answer before seeing the data.

What this file does instead
---------------------------
It fits an ordinal Gaussian process. A single latent function ``f`` is given a Gaussian-process
prior over the stimulation parameters, and the observed category is generated by comparing that
latent value against a set of learned cutpoints:

    P(y = k | f) = Phi(c_k - f) - Phi(c_{k-1} - f)

with ``Phi`` the standard normal cumulative distribution function, ``c_0 = 0`` fixed for
identifiability and the remaining cutpoints obtained by adding positive learned increments. This
is the ordered-probit likelihood, and the implementation follows the one in Meta's AEPsych
package, which is the closest published analogue to this problem because it was built for
adaptive psychophysics experiments in which a human being rates a stimulus on an ordered scale.
The two files adapted here are ``aepsych/likelihoods/ordinal.py`` (the cutpoint likelihood, and
the convention that the first cutpoint is fixed at zero) and ``aepsych/models/ordinal_gp.py``
(the variational ordinal GP, the decision to omit an output scale from the kernel because the
latent scale and the cutpoint spacing are not separately identifiable, and the closed-form
moment-matched predictive probabilities). AEPsych is MIT-licensed Meta code; the approach is
adapted rather than copied, and the correspondence is recorded in comments at each place it
matters.

Three properties of this structure matter for the clinical question:

1.  It imposes no monotone dose-response. The latent function is free to rise, fall or stay flat
    in any input, so the model can report that amplitude does not predict severity if that is
    what the data show.
2.  Its output is a probability of a category, not a score. "The posterior probability of a
    moderate-or-worse event at this setting is 4 percent, with a 90 percent credible interval
    from 1 to 12 percent" is a sentence a clinician can act on. "Predicted severity 0.31" is not.
3.  Because the latent function has a Gaussian posterior and the probability of
    moderate-or-worse is a monotone increasing transform of it, credible intervals on that
    probability are available in closed form by transforming the latent quantiles. No sampling
    is needed and the intervals are exact given the variational posterior.

Unknown is not the same as safe
-------------------------------
This is the single most important behaviour in the file. Far from any observation the
variational posterior reverts to the prior: the latent mean returns to the fitted constant and
the latent variance rises to the prior variance, which for a Matern kernel without an output
scale is exactly 1. Because moderate-or-worse events are rare overall, that fitted constant
corresponds to a LOW probability. Reading the estimated probability alone would therefore report
an unobserved region as low-risk, which is precisely the error that must not be made: it would
tell a clinician that a setting nobody has ever delivered is safe, on the strength of the
overall base rate.

Two separate mechanisms prevent that, and it is worth being clear about which does what, because
they fail in different circumstances. The first is the credible interval. Where the latent
variance has reverted to 1 the interval on the probability is very wide, so its upper end
exceeds any reasonable tolerance and the cell cannot be called safe. This is the mechanism that
does most of the work. The second is an explicit requirement for local evidence, which exists
because the first is not guaranteed: if the fitted cutpoints are far apart relative to the
latent scale, a reverted region can have both a low estimated probability and an interval narrow
enough to clear the tolerance. The evidence requirement also matters independently for the
cumulative safe set in :class:`SafeSetTracker`, where an admission can never be withdrawn and
must therefore not rest on the absence of contradicting data.

:meth:`OrdinalSeverityGP.classify` therefore requires two separate conditions before it will
call a cell safe. The upper end of the credible interval on the probability of moderate-or-worse
must fall below a stated threshold, AND the cell must carry a minimum amount of local evidence,
measured as the sum of the fitted kernel's correlation between that cell and every training
observation. That second quantity, ``n_eff``, is an effective local sample size: it equals
roughly the number of observations that are close enough, on the model's own fitted length
scales, to say anything about this cell. A cell that fails either condition without failing the
probability condition in the unsafe direction is labelled ``unknown``, which is a third state
distinct from both ``safe`` and ``elevated``.

Missing labels are missing
--------------------------
Steps whose severity could not be coded are dropped, never recoded as "none". A step read as
no-side-effect would tell the model that an untested region was tolerated, which is the same
category of error as calling an unobserved region safe. :func:`prepare_coded_steps` enforces
this and additionally separates steps whose "none" label came from an explicit coding decision
from steps that were never put through the coding pass at all, because those two are not the
same kind of evidence and the difference turns out to matter here.

Relationship to SAFE-OPT
------------------------
The safe-set bookkeeping in :class:`SafeSetTracker` follows the update rule of Sarikhani et
al.'s SAFE-OPT as implemented in Cole's MATLAB reference (``code/safe_opt_memory/
safe_opt_update_ND.m``), in which the safe set is CUMULATIVE: a grid cell that has ever
qualified stays in the set permanently, so the set grows monotonically and cannot oscillate
between iterations. Only that update rule is borrowed. The model structure is not: in that
reference the safety model and the objective model are literally the same Gaussian process over
a single discriminant score, whereas here pain relief and side-effect severity are different
quantities measured on different scales with different likelihoods. The cumulative rule is
offered but is NOT the default, for the reason given in :class:`SafeSetTracker`.
"""
from __future__ import annotations

import math

import numpy as np

from .surrogate_torch import (
    _MIN_LENGTHSCALE,
    _PRIOR_SCALE,
    dim_scaled_prior_loc,
    require_torch,
    torch_available,
)

# Everything torch-related is imported behind a captured exception, exactly as in
# ``surrogate_torch``. Importing this module on a machine without the PyTorch stack must succeed,
# so that a container which ships without torch can still import the package and still use the
# non-modelled parts of the safety reasoning. Nothing at module scope may touch a torch symbol.
_IMPORT_ERROR: Exception | None = None
try:  # pragma: no cover - the covered path is the one where the import succeeds
    import torch
    from gpytorch.constraints import GreaterThan, Positive
    from gpytorch.kernels import MaternKernel
    from gpytorch.likelihoods import Likelihood
    from gpytorch.means import ConstantMean
    from gpytorch.mlls import VariationalELBO
    from gpytorch.models import ApproximateGP
    from gpytorch.priors import LogNormalPrior
    from gpytorch.variational import CholeskyVariationalDistribution, VariationalStrategy
    from torch.distributions import Categorical, Normal
except Exception as exc:  # pragma: no cover
    _IMPORT_ERROR = exc


#: The ordered severity scale used throughout the acute testing record, lowest first. The order
#: is the whole content of an ordinal model, so it is defined once here and never re-typed.
SEVERITY_LEVELS = ("none", "mild", "moderate", "severe")

#: The category at or above which an event is treated as clinically unacceptable. This matches
#: ``objective.SE_HARD_REJECT``, which makes moderate and severe hard-infeasible for the
#: objective surrogate.
DEFAULT_ADVERSE_LEVEL = "moderate"

#: Default upper bound on the probability of a moderate-or-worse event for a cell to be called
#: safe. This is a stated tolerance, not an estimate: it says that a one-in-twenty chance of a
#: moderate event is the most a clinician is willing to accept at a proposed setting. It is
#: exposed as an argument everywhere so that the choice is visible and can be changed.
DEFAULT_P_ADVERSE_MAX = 0.05

#: Default minimum effective local sample size for a cell to be eligible to be called safe. A
#: value of 3 means the fitted kernel must place the equivalent of three whole observations
#: within its own correlation range of the cell. Below that the cell is reported as unknown
#: however low its estimated probability is.
DEFAULT_MIN_EVIDENCE = 3.0


def ordinal_torch_available() -> bool:
    """Whether the PyTorch and GPyTorch stack needed by this module imported successfully."""
    return _IMPORT_ERROR is None and torch_available()


def require_ordinal_torch() -> None:
    """Raise an informative error if the PyTorch stack is unavailable, otherwise do nothing.

    This module's own import failure is checked BEFORE the one in ``surrogate_torch``, so that a
    caller of the ordinal model is told about the ordinal model rather than about the BoTorch
    objective surrogate. Both fail for the same underlying reason, but naming the wrong
    component sends the reader to the wrong file.
    """
    if _IMPORT_ERROR is not None:
        raise ImportError(
            "The ordinal safety model requires the packages torch and gpytorch, and importing "
            f"them failed with: {type(_IMPORT_ERROR).__name__}: {_IMPORT_ERROR}. Install them "
            "with `pip install gpytorch`, which pulls torch and linear_operator as "
            "dependencies. The rest of StimOptimizer, including the label handling in "
            "prepare_coded_steps and the safe-set bookkeeping in SafeSetTracker, works without "
            "them."
        ) from _IMPORT_ERROR
    require_torch()


# --- data preparation -------------------------------------------------------------------------
def encode_severity(labels, *, levels=SEVERITY_LEVELS):
    """Map severity label strings onto their integer rank, with anything unrecognised as -1.

    Returns an integer array in which ``-1`` marks a step that carries no usable severity code,
    whether because the field was empty, because it held a missing-value marker, or because it
    held a string outside the ordered scale. The caller is expected to drop those rows. They are
    NOT mapped to zero: a step read as no-side-effect is a positive claim that the setting was
    tolerated, and inventing that claim for a step nobody coded is the error this whole module
    exists to avoid.
    """
    order = {name: i for i, name in enumerate(levels)}
    out = np.full(len(labels), -1, dtype=int)
    for i, v in enumerate(labels):
        if v is None:
            continue
        if isinstance(v, float) and math.isnan(v):
            continue
        out[i] = order.get(str(v).strip().lower(), -1)
    return out


def prepare_coded_steps(frame, *, features=("rate_hz", "amp_L", "pw_L"),
                        severity_col="se_severity", coded_col="coded",
                        procedural_col="procedural", amp_col="amp_L",
                        require_stim_on=True, explicit_only=False):
    """Turn the coded acute-step table into the arrays :class:`OrdinalSeverityGP` consumes.

    Parameters
    ----------
    frame
        A pandas DataFrame of coded acute steps, one row per delivered test step.
    features
        Column names, in order, to use as the model's inputs.
    severity_col
        Column holding the ordered severity label.
    coded_col
        Optional column marking whether the row went through the manual coding pass. In the
        RCS08 file this is ``True`` for a row that was coded, ``False`` for a row a coder looked
        at and could not classify, and missing for a row that was never presented to a coder at
        all. Those three are genuinely different and are reported separately below.
    procedural_col
        Optional boolean column marking steps that were part of a procedure such as impedance
        checking rather than a therapeutic test. Procedural steps are excluded, because a
        severity label recorded during a procedure is not a statement about the tolerability of
        a therapeutic setting.
    require_stim_on
        Drop rows whose amplitude is zero. Those rows are real observations, and the rate at
        which adverse events occur in them is an important comparison, but the frequency and
        pulse width recorded alongside a zero amplitude do not describe stimulation that was
        actually delivered, so putting them into a model over frequency and pulse width would
        associate an adverse event with a setting the participant never received. The zero
        amplitude rows are returned separately in the audit dictionary so that the comparison
        can still be made.
    explicit_only
        Keep only rows whose ``coded_col`` is exactly ``True``. This is the sensitivity analysis
        for the concern described in the audit: a "none" label on a row that was never coded is
        an absence of a note rather than a recorded observation of no side effect.

    Returns
    -------
    A dictionary with ``X`` of shape ``(n, len(features))``, ``y`` of integer severity ranks,
    and an ``audit`` sub-dictionary recording every row that was dropped and why. Nothing is
    dropped silently.
    """
    import pandas as pd  # local import: pandas is a hard dependency of the module but not of

    # this function's callers in the container, and keeping it local documents that.
    d = pd.DataFrame(frame).copy()
    n_total = len(d)

    audit = {"n_input_rows": int(n_total)}

    if coded_col in d.columns:
        coded = d[coded_col]
        audit["n_coded_true"] = int((coded == True).sum())        # noqa: E712 - pandas mask
        audit["n_coded_false"] = int((coded == False).sum())      # noqa: E712 - pandas mask
        audit["n_never_presented_to_coder"] = int(coded.isna().sum())
        if severity_col in d.columns:
            audit["n_none_from_never_coded"] = int(
                (coded.isna() & (d[severity_col].astype(str).str.lower() == "none")).sum())
    if procedural_col in d.columns:
        procedural = d[procedural_col] == True                    # noqa: E712 - pandas mask
        audit["n_procedural_dropped"] = int(procedural.sum())
        d = d[~procedural]
    if explicit_only and coded_col in d.columns:
        keep = d[coded_col] == True                               # noqa: E712 - pandas mask
        audit["n_dropped_not_explicitly_coded"] = int((~keep).sum())
        d = d[keep]

    y_all = encode_severity(d[severity_col].tolist())
    audit["n_severity_unknown_dropped"] = int((y_all < 0).sum())
    d = d[y_all >= 0]
    y = y_all[y_all >= 0]

    finite = np.isfinite(d[list(features)].to_numpy(dtype=float)).all(axis=1)
    audit["n_incomplete_features_dropped"] = int((~finite).sum())
    d, y = d[finite], y[finite]

    if amp_col in d.columns:
        on = d[amp_col].to_numpy(dtype=float) > 0.0
        audit["n_amplitude_zero"] = int((~on).sum())
        if (~on).any():
            y_off = y[~on]
            audit["adverse_rate_at_zero_amplitude"] = float(
                np.mean(y_off >= SEVERITY_LEVELS.index(DEFAULT_ADVERSE_LEVEL)))
        else:
            audit["adverse_rate_at_zero_amplitude"] = float("nan")
        if require_stim_on:
            d, y = d[on], y[on]

    X = d[list(features)].to_numpy(dtype=float)
    audit["n_fitted"] = int(len(y))
    audit["features"] = list(features)
    audit["label_counts"] = {SEVERITY_LEVELS[k]: int((y == k).sum())
                             for k in range(len(SEVERITY_LEVELS))}
    return {"X": X, "y": y, "frame": d, "audit": audit}


# --- the likelihood ----------------------------------------------------------------------------
def _make_ordinal_likelihood(n_levels):
    """Build the ordered-probit likelihood. Separated out so it can be built lazily."""
    require_ordinal_torch()

    class OrdinalLikelihood(Likelihood):
        """Ordered-probit likelihood with learned cutpoints.

        Adapted from ``aepsych/likelihoods/ordinal.py`` (Meta, MIT licence). Two conventions are
        taken from there and both are load-bearing. The first cutpoint is fixed at zero, because
        adding a constant to the latent function and the same constant to every cutpoint leaves
        the likelihood unchanged, so without a fixed reference the model is not identified. The
        remaining cutpoints are built by accumulating positive increments, which guarantees they
        stay in ascending order for any value the optimiser proposes, rather than relying on an
        ordering constraint that could be violated mid-optimisation.

        One addition relative to the reference: the category probabilities are clamped away from
        zero before being handed to the categorical distribution. Differences of two normal
        cumulative distribution functions can come out as a small negative number in floating
        point when the two cutpoints are close, which makes the categorical distribution raise
        rather than returning a very small log probability, and that failure appears only
        intermittently during optimisation.
        """

        def __init__(self, n_levels):
            super().__init__()
            if int(n_levels) < 3:
                raise ValueError("an ordinal likelihood needs at least three levels")
            self.n_levels = int(n_levels)
            self.register_parameter(
                name="raw_cutpoint_deltas",
                parameter=torch.nn.Parameter(torch.ones(self.n_levels - 2, dtype=torch.double)))
            self.register_constraint("raw_cutpoint_deltas", Positive())
            self._link = Normal(torch.tensor(0.0, dtype=torch.double),
                                torch.tensor(1.0, dtype=torch.double)).cdf

        @property
        def cutpoints(self):
            deltas = self.raw_cutpoint_deltas_constraint.transform(self.raw_cutpoint_deltas)
            zero = torch.zeros(1, dtype=deltas.dtype, device=deltas.device)
            return torch.cat((zero, torch.cumsum(deltas, 0)))

        def link(self, z):
            return self._link(z)

        def category_probs(self, f):
            """Probabilities of every category given latent values ``f``, shape ``(..., K)``."""
            c = self.cutpoints
            cols = [self.link(c[0] - f)]
            for i in range(1, self.n_levels - 1):
                cols.append(self.link(c[i] - f) - self.link(c[i - 1] - f))
            cols.append(1.0 - self.link(c[-1] - f))
            probs = torch.stack(cols, dim=-1)
            return probs.clamp_min(1e-12)

        def forward(self, function_samples, *params, **kwargs):
            return Categorical(probs=self.category_probs(function_samples))

    return OrdinalLikelihood(n_levels)


def _make_variational_gp(inducing, n_dim, prior_loc, prior_scale, min_lengthscale, nu):
    """Build the variational GP over the latent severity function."""
    require_ordinal_torch()

    class _OrdinalVariationalGP(ApproximateGP):
        """Sparse variational GP with a constant mean and an ARD Matern kernel.

        Structure follows ``aepsych/models/ordinal_gp.py`` and its variational base class, with
        two deliberate departures.

        The kernel carries NO output scale. In an ordinal model the vertical scale of the latent
        function and the spacing of the cutpoints multiply together in the likelihood, so only
        their ratio is identified; letting both be free produces a ridge in the objective along
        which the fit wanders without improving. AEPsych removes the output scale for exactly
        this reason and the same choice is made here. The consequence worth remembering is that
        the prior variance of the latent function is therefore fixed at 1, so a region with no
        data has a latent standard deviation of 1 and not more, which is why an evidence
        requirement is imposed separately rather than reading uncertainty off the variance
        alone.

        The kernel is Matern with smoothness 3/2 rather than the squared exponential AEPsych
        defaults to, matching the objective surrogate in this module and the deployed systems it
        follows, and the length-scale prior is the dimension-scaled log-normal of Hvarfner et
        al. (2024) that the objective surrogate also uses, rather than AEPsych's gamma prior. Two
        models in one pipeline disagreeing about how smooth the same parameter space is would be
        difficult to defend.
        """

        def __init__(self):
            variational_distribution = CholeskyVariationalDistribution(
                inducing.size(0)).to(inducing)
            strategy = VariationalStrategy(
                self, inducing, variational_distribution, learn_inducing_locations=False)
            super().__init__(strategy)
            self.mean_module = ConstantMean()
            self.covar_module = MaternKernel(
                nu=float(nu), ard_num_dims=int(n_dim),
                lengthscale_prior=LogNormalPrior(float(prior_loc), float(prior_scale)),
                lengthscale_constraint=GreaterThan(float(min_lengthscale)))

        def forward(self, x):
            from gpytorch.distributions import MultivariateNormal
            return MultivariateNormal(self.mean_module(x), self.covar_module(x))

    return _OrdinalVariationalGP().double()


# --- the model ----------------------------------------------------------------------------------
class OrdinalSeverityGP:
    """Ordinal Gaussian-process model of side-effect severity over stimulation parameters.

    Parameters
    ----------
    features
        Names of the input columns, in the order the columns of ``X`` appear. Used only for
        reporting, so that every returned dictionary is self-describing.
    log2_features
        Names of features to place on a base-2 logarithmic axis before standardising. Stimulation
        frequency belongs here: its effects are conventionally multiplicative, and one length
        scale cannot serve 10 Hz and 180 Hz on a linear axis. This is the same treatment
        :class:`StimOptimizer.routines.surrogate.ParameterGrid` gives frequency.
    n_levels
        Number of ordered severity categories. Four for the scale used here.
    nu
        Matern smoothness parameter, 3/2 by default to match the objective surrogate.
    prior_loc, prior_scale
        Location and scale of the log-normal prior on each length scale, on the log scale.
        ``prior_loc=None`` uses the dimension-scaled default of Hvarfner et al. (2024).
    n_inducing
        Maximum number of inducing points. When the training data contain fewer distinct settings
        than this, every distinct setting is used and the sparse approximation is exact at the
        data. The acute record contains far fewer distinct settings than steps, so this is the
        usual case, and the default of 256 is set above the 188 distinct settings in the RCS08
        record so that the usual case is the exact one. This is not a free performance dial: with
        the inducing set capped at 128 and therefore subsampled, the same data give fitted length
        scales of roughly 1.25, 3.35 and 5.77 against 0.38, 0.46 and 2.47 with every distinct
        setting retained. A subsampled inducing set makes the model look much smoother than the
        data support, so lower this only with a reason.
    random_state
        Seed for the variational initialisation and for the Monte Carlo samples the evidence
        lower bound uses. Fitting is deterministic given the seed.
    """

    def __init__(self, features, *, log2_features=("rate_hz",), n_levels=len(SEVERITY_LEVELS),
                 nu=1.5, prior_loc=None, prior_scale=_PRIOR_SCALE,
                 min_lengthscale=_MIN_LENGTHSCALE, n_inducing=256, random_state=0):
        require_ordinal_torch()
        self.features = tuple(features)
        self.log2_features = tuple(f for f in log2_features if f in self.features)
        self.n_levels = int(n_levels)
        self.nu = float(nu)
        self.prior_loc = prior_loc
        self.prior_scale = float(prior_scale)
        self.min_lengthscale = float(min_lengthscale)
        self.n_inducing = int(n_inducing)
        self.random_state = int(random_state)
        self.model_ = None

    # --- input handling ------------------------------------------------------------------
    def _raw_to_axes(self, X):
        """Apply the per-feature log2 transform, before standardisation."""
        X = np.atleast_2d(np.asarray(X, float))
        if X.shape[1] != len(self.features):
            raise ValueError(f"expected {len(self.features)} columns {self.features}, "
                             f"got {X.shape[1]}")
        Z = X.copy()
        for j, name in enumerate(self.features):
            if name in self.log2_features:
                if np.any(Z[:, j] <= 0):
                    raise ValueError(
                        f"non-positive value in {name!r}, which is on a log2 axis; a zero "
                        "frequency or pulse width is not a stimulation setting and should have "
                        "been dropped before fitting")
                Z[:, j] = np.log2(Z[:, j])
        return Z

    def transform(self, X):
        """Map raw parameter values onto the standardised axes the kernel sees."""
        if self.model_ is None and not hasattr(self, "_loc"):
            raise RuntimeError("OrdinalSeverityGP is not fitted")
        return (self._raw_to_axes(X) - self._loc) / self._scale

    # --- fitting --------------------------------------------------------------------------
    def fit(self, X, y, *, n_iter=600, lr=0.1, num_likelihood_samples=64, verbose=False):
        """Fit the latent GP and the cutpoints jointly by maximising the evidence lower bound.

        ``y`` must be integer severity ranks in ``0 .. n_levels - 1``. Rows with a missing label
        must already have been removed; see :func:`prepare_coded_steps`. Passing a negative rank
        raises rather than being silently treated as the lowest category.

        Optimisation is Adam on the full data set, which is appropriate at this sample size
        (hundreds of steps, not millions). The evidence lower bound is stochastic because the
        expected log likelihood under a non-Gaussian likelihood is estimated by sampling the
        latent function; ``num_likelihood_samples`` controls how many samples, and the torch
        seed is fixed so a given call is reproducible.
        """
        import gpytorch

        X = np.atleast_2d(np.asarray(X, float))
        y = np.asarray(y).ravel().astype(int)
        if X.shape[0] != y.size:
            raise ValueError("X and y must have matching length")
        if y.size < 5:
            raise ValueError(f"need at least 5 labelled steps to fit, got {y.size}")
        if y.min() < 0:
            raise ValueError(
                "negative severity rank passed to fit. A rank of -1 marks a step whose severity "
                "could not be coded; such steps carry no information about tolerability and "
                "must be dropped, not recoded as 'none'.")
        if y.max() >= self.n_levels:
            raise ValueError(f"severity rank {int(y.max())} exceeds n_levels={self.n_levels}")

        A = self._raw_to_axes(X)
        self._loc = A.mean(axis=0)
        self._scale = np.maximum(A.std(axis=0, ddof=0), 1e-9)
        Z = (A - self._loc) / self._scale

        # Inducing points at the DISTINCT settings actually delivered. When every distinct
        # setting is an inducing point the sparse approximation introduces no additional error at
        # the observed locations, and repeated steps at the same setting cost nothing extra.
        uniq = np.unique(np.round(Z, 9), axis=0)
        if uniq.shape[0] > self.n_inducing:
            rng = np.random.default_rng(self.random_state)
            uniq = uniq[rng.choice(uniq.shape[0], self.n_inducing, replace=False)]
        self.n_inducing_used_ = int(uniq.shape[0])

        torch.manual_seed(self.random_state)
        Zt = torch.as_tensor(Z, dtype=torch.double)
        yt = torch.as_tensor(y, dtype=torch.long)
        ind = torch.as_tensor(uniq, dtype=torch.double)

        prior_loc = (dim_scaled_prior_loc(Z.shape[1]) if self.prior_loc is None
                     else float(self.prior_loc))
        model = _make_variational_gp(ind, Z.shape[1], prior_loc, self.prior_scale,
                                     self.min_lengthscale, self.nu)
        likelihood = _make_ordinal_likelihood(self.n_levels).double()
        model.train()
        likelihood.train()
        mll = VariationalELBO(likelihood, model, num_data=yt.numel())
        opt = torch.optim.Adam(list(model.parameters()) + list(likelihood.parameters()), lr=lr)

        trace = []
        with gpytorch.settings.num_likelihood_samples(int(num_likelihood_samples)):
            for it in range(int(n_iter)):
                opt.zero_grad()
                loss = -mll(model(Zt), yt)
                loss.backward()
                opt.step()
                trace.append(float(loss.detach()))
                if verbose and it % 100 == 0:
                    print(f"iter {it} loss {trace[-1]:.5f}")

        model.eval()
        likelihood.eval()
        self.model_, self.likelihood_ = model, likelihood
        self.X_, self.y_, self.Z_ = X, y, Z
        self.loss_trace_ = np.asarray(trace, float)
        return self

    def _check(self):
        if self.model_ is None:
            raise RuntimeError("OrdinalSeverityGP is not fitted")

    # --- posterior -------------------------------------------------------------------------
    def predict_latent(self, X):
        """Posterior mean and standard deviation of the latent severity function.

        The latent function has no clinical units. It is reported because its standard deviation
        is the cleanest single summary of how much the model knows at a location: it starts at
        the prior value of 1 where there are no data and shrinks toward zero where there are
        many.
        """
        self._check()
        Zq = torch.as_tensor(self.transform(X), dtype=torch.double)
        with torch.no_grad():
            post = self.model_(Zq)
            return (post.mean.numpy(), post.variance.clamp_min(0.0).sqrt().numpy())

    def predict_proba(self, X):
        """Posterior predictive probability of each severity category, shape ``(n, n_levels)``.

        Computed in closed form rather than by sampling. For a probit link the integral of
        ``Phi(c - f)`` against a Gaussian posterior on ``f`` with mean ``m`` and variance ``v``
        is exactly ``Phi((c - m) / sqrt(1 + v))``, so the posterior predictive category
        probabilities require no Monte Carlo at all. This is the ``calculate_probs`` identity in
        ``aepsych/models/ordinal_gp.py``.
        """
        self._check()
        m, sd = self.predict_latent(X)
        s = np.sqrt(1.0 + sd ** 2)
        c = self.cutpoints
        from scipy.stats import norm
        cols = [norm.cdf((c[0] - m) / s)]
        for i in range(1, self.n_levels - 1):
            cols.append(norm.cdf((c[i] - m) / s) - norm.cdf((c[i - 1] - m) / s))
        cols.append(1.0 - norm.cdf((c[-1] - m) / s))
        return np.clip(np.column_stack(cols), 0.0, 1.0)

    def p_at_least(self, X, level=DEFAULT_ADVERSE_LEVEL, *, credible_mass=0.90):
        """Probability of a severity of ``level`` or worse, with a credible interval.

        Returns a dictionary with ``mean`` (the posterior predictive probability, integrating
        over the latent uncertainty), ``lower`` and ``upper`` (the ends of the equal-tailed
        credible interval on that probability), ``width`` (their difference) and ``latent_sd``.

        The interval is exact given the variational posterior and needs no sampling. For a
        four-level scale the probability of moderate-or-worse is ``1 - Phi(c_1 - f)``, which is
        strictly increasing in the latent value ``f``. A strictly increasing transform maps the
        quantiles of ``f`` onto the quantiles of the probability, so the interval endpoints are
        obtained by pushing the latent quantiles through the same expression.

        Note the difference between ``mean`` and the midpoint of the interval. ``mean`` averages
        the probability over the latent uncertainty and is the number to quote as the model's
        estimate; the interval says how much that estimate would move if the latent function
        were pinned down. Where there are no data the two diverge substantially, and that
        divergence is the signal that the region is unknown rather than benign.
        """
        self._check()
        from scipy.stats import norm
        k = level if isinstance(level, int) else SEVERITY_LEVELS.index(str(level).lower())
        if not 1 <= k < self.n_levels:
            raise ValueError(f"level must be between 1 and {self.n_levels - 1}, got {level!r}")
        c = self.cutpoints[k - 1]
        m, sd = self.predict_latent(X)
        z = norm.ppf(0.5 + float(credible_mass) / 2.0)
        f_lo, f_hi = m - z * sd, m + z * sd
        mean = 1.0 - norm.cdf((c - m) / np.sqrt(1.0 + sd ** 2))
        lower = 1.0 - norm.cdf(c - f_lo)
        upper = 1.0 - norm.cdf(c - f_hi)
        return {"mean": mean, "lower": lower, "upper": upper, "width": upper - lower,
                "latent_sd": sd, "credible_mass": float(credible_mass),
                "level": SEVERITY_LEVELS[k] if k < len(SEVERITY_LEVELS) else int(k)}

    def evidence(self, X):
        """Effective local sample size at each query point.

        Defined as the sum, over every training observation, of the fitted kernel's correlation
        between that observation and the query point. Because the kernel has no output scale its
        value at zero separation is exactly 1, so this quantity is on the scale of a count of
        observations: a query point sitting on top of five identical training steps returns
        approximately 5, and a query point far outside the fitted length scales in any dimension
        returns approximately 0.

        This is what makes "no data here" expressible independently of the posterior
        probability. It uses the model's OWN fitted length scales, so a dimension the model has
        learned is irrelevant does not contribute to the distance and does not make a cell look
        unsupported for no reason.
        """
        self._check()
        Zq = torch.as_tensor(self.transform(X), dtype=torch.double)
        Zt = torch.as_tensor(self.Z_, dtype=torch.double)
        with torch.no_grad():
            K = self.model_.covar_module(Zq, Zt).to_dense()
            return K.sum(dim=1).clamp_min(0.0).numpy()

    def classify(self, X, *, level=DEFAULT_ADVERSE_LEVEL, p_max=DEFAULT_P_ADVERSE_MAX,
                 min_evidence=DEFAULT_MIN_EVIDENCE, credible_mass=0.90):
        """Three-state safety label per query point: ``safe``, ``unknown`` or ``elevated``.

        ``elevated``
            The LOWER end of the credible interval on the probability of a ``level``-or-worse
            event is above ``p_max``. The model is confident the risk exceeds tolerance.
        ``safe``
            The UPPER end of that interval is below ``p_max`` AND the effective local sample
            size is at least ``min_evidence``. Both conditions are required. Dropping the second
            would let the model call an unvisited region safe on the strength of the overall
            base rate, which is the failure mode described in the module docstring.
        ``unknown``
            Everything else: either the interval straddles the tolerance, or it is comfortably
            below it but rests on too little local data to be believed.

        Returns a dictionary with the ``label`` array and the arrays it was derived from, so a
        caller can see exactly which condition decided each cell.
        """
        p = self.p_at_least(X, level=level, credible_mass=credible_mass)
        n_eff = self.evidence(X)
        label = np.full(len(n_eff), "unknown", dtype="<U8")
        label[(p["upper"] < float(p_max)) & (n_eff >= float(min_evidence))] = "safe"
        label[p["lower"] > float(p_max)] = "elevated"
        return {"label": label, "p_mean": p["mean"], "p_lower": p["lower"],
                "p_upper": p["upper"], "ci_width": p["width"], "n_eff": n_eff,
                "latent_sd": p["latent_sd"], "p_max": float(p_max),
                "min_evidence": float(min_evidence), "credible_mass": float(credible_mass)}

    # --- fitted quantities ------------------------------------------------------------------
    @property
    def cutpoints(self):
        """The learned cutpoints on the latent scale, ascending, with the first fixed at zero."""
        self._check()
        with torch.no_grad():
            return self.likelihood_.cutpoints.numpy()

    @property
    def lengthscales(self):
        """Fitted length scale per input dimension, on the standardised axes."""
        self._check()
        with torch.no_grad():
            return self.model_.covar_module.lengthscale.numpy().ravel()

    @property
    def hyperparameters(self):
        """Fitted quantities in a single dictionary, for logging and for the written report."""
        self._check()
        with torch.no_grad():
            mean_const = float(self.model_.mean_module.constant)
        return {
            "backend": "gpytorch-variational-ordinal",
            "features": list(self.features),
            "log2_features": list(self.log2_features),
            "n_levels": self.n_levels,
            "cutpoints": self.cutpoints.tolist(),
            "lengthscale": self.lengthscales.tolist(),
            "lengthscale_by_feature": dict(zip(self.features, self.lengthscales.tolist())),
            "mean_constant": mean_const,
            "n_inducing_used": self.n_inducing_used_,
            "n_observations": int(self.y_.size),
            "final_negative_elbo": float(self.loss_trace_[-1]),
            "kernel": (f"Matern(nu={self.nu}, ard, lengthscale="
                       f"{np.round(self.lengthscales, 4).tolist()}) with no output scale, "
                       "because latent scale and cutpoint spacing are not separately "
                       "identifiable"),
        }

    def training_fit(self):
        """In-sample agreement between predicted and observed categories.

        Reports the mean predicted probability assigned to the category that actually occurred,
        and the observed against predicted rate of adverse events. This is an in-sample check
        and is therefore optimistic; it is here to catch a fit that has gone wrong, not to
        establish predictive performance.
        """
        self._check()
        P = self.predict_proba(self.X_)
        k = SEVERITY_LEVELS.index(DEFAULT_ADVERSE_LEVEL)
        return {
            "mean_prob_of_observed_category": float(P[np.arange(len(self.y_)), self.y_].mean()),
            "observed_adverse_rate": float(np.mean(self.y_ >= k)),
            "predicted_adverse_rate": float(P[:, k:].sum(axis=1).mean()),
            "n": int(self.y_.size),
        }


# --- safe-set bookkeeping ------------------------------------------------------------------
class SafeSetTracker:
    """Maintains the safe set across successive model updates, recomputed or cumulative.

    Two update rules are offered, and which one is used is a real scientific choice rather than
    an implementation detail.

    ``mode="recomputed"`` (the default)
        The safe set is whatever the current model says is safe. A cell can leave the set if new
        data make it look worse. This is the honest reading of the current posterior and it is
        the default here.

    ``mode="cumulative"``
        A cell that has ever qualified stays in the set permanently. This is the rule in Cole's
        MATLAB SAFE-OPT reference, ``code/safe_opt_memory/safe_opt_update_ND.m``, where the
        update line reads ``safe_set = any([safe_set  Q_low > threshold], 2)``: the disjunction
        with the previous set is what makes the set grow monotonically. Its advantage is
        stability. A set recomputed from scratch at every iteration can gain and lose cells
        between iterations, and a recommendation that appears and disappears is difficult for a
        clinician to act on.

    Why cumulative is offered but not the default. A set that never shrinks is only sound if the
    model that admitted each cell was conservative, because an admission made on a wrong
    posterior can never be withdrawn. With an ordinal likelihood fitted to a few hundred steps,
    of which very few sit at the top of the amplitude range, a cell can be admitted on thin
    evidence. Admission is therefore gated on the evidence requirement as well as the
    probability bound, which is the same ``min_evidence`` condition
    :meth:`OrdinalSeverityGP.classify` applies; a cell that was only ever called safe because
    nothing contradicted it can never enter the cumulative set in the first place.

    The tracker also reports whether the resulting set is CONTIGUOUS in amplitude. A clinician
    ramps amplitude upward through intermediate values, so a cell that is only reachable by
    passing through a band the model does not call safe is not programmable, whatever the model
    thinks of the cell itself. :meth:`contiguity_violations` lists the parameter combinations
    where that happens and :meth:`lower_interval` returns the largest programmable subset.
    """

    def __init__(self, *, mode="recomputed"):
        if mode not in ("recomputed", "cumulative"):
            raise ValueError("mode must be either 'recomputed' or 'cumulative'")
        self.mode = mode
        self.mask_ = None
        self.n_updates_ = 0

    def update(self, label, n_eff=None, *, min_evidence=DEFAULT_MIN_EVIDENCE):
        """Fold one classification into the tracked set and return the current mask.

        ``label`` is the string array from :meth:`OrdinalSeverityGP.classify`. ``n_eff`` is the
        effective local sample size from the same call; it is required in cumulative mode,
        because that is where the evidence gate is applied, and ignored in recomputed mode where
        ``classify`` has already applied it.
        """
        label = np.asarray(label)
        current = label == "safe"
        if self.mode == "recomputed" or self.mask_ is None:
            if self.mode == "cumulative":
                if n_eff is None:
                    raise ValueError(
                        "cumulative mode needs n_eff, because admission to a set that never "
                        "shrinks must be gated on evidence and not on probability alone")
                current = current & (np.asarray(n_eff, float) >= float(min_evidence))
            self.mask_ = current.copy()
        else:
            if n_eff is None:
                raise ValueError("cumulative mode needs n_eff at every update")
            admitted = current & (np.asarray(n_eff, float) >= float(min_evidence))
            self.mask_ = self.mask_ | admitted
        self.n_updates_ += 1
        return self.mask_.copy()

    @staticmethod
    def contiguity_violations(mask, X, amp_col=1, tol=1e-9):
        """Parameter combinations where the mask is not a lower interval in amplitude.

        For each distinct combination of the non-amplitude columns of ``X``, the amplitudes
        marked safe should run from the lowest available value up to some ceiling with no gap. A
        gap means a proposed setting sits above a band the model does not call safe, so the
        clinician cannot ramp to it. Returns a list of dictionaries, one per offending
        combination, each naming the gap.
        """
        mask = np.asarray(mask, bool)
        X = np.atleast_2d(np.asarray(X, float))
        others = np.delete(X, amp_col, axis=1)
        keys, inverse = np.unique(np.round(others, 9), axis=0, return_inverse=True)
        out = []
        for g in range(keys.shape[0]):
            sel = inverse == g
            amps = X[sel, amp_col]
            m = mask[sel]
            order = np.argsort(amps)
            amps, m = amps[order], m[order]
            if not m.any():
                continue
            last = int(np.flatnonzero(m).max())
            if not m[: last + 1].all():
                gap = amps[: last + 1][~m[: last + 1]]
                out.append({"other_columns": keys[g].tolist(),
                            "unsafe_amplitudes_below_a_safe_one": gap.tolist(),
                            "highest_safe_amplitude": float(amps[last])})
        return out

    @staticmethod
    def lower_interval(mask, X, amp_col=1):
        """Truncate the mask to the largest programmable subset: a lower interval in amplitude.

        At each distinct combination of the other parameters the mask is cut at the first
        amplitude that is not safe, discarding everything above it. This never adds a cell, so
        it cannot make the set less conservative; it only removes cells the clinician could not
        have reached anyway.
        """
        mask = np.asarray(mask, bool)
        X = np.atleast_2d(np.asarray(X, float))
        others = np.delete(X, amp_col, axis=1)
        keys, inverse = np.unique(np.round(others, 9), axis=0, return_inverse=True)
        out = np.zeros_like(mask)
        for g in range(keys.shape[0]):
            sel = np.flatnonzero(inverse == g)
            order = sel[np.argsort(X[sel, amp_col])]
            m = mask[order]
            first_bad = np.flatnonzero(~m)
            stop = len(m) if first_bad.size == 0 else int(first_bad[0])
            out[order[:stop]] = True
        return out


def compare_safe_set_rules(model, X_sequence, *, level=DEFAULT_ADVERSE_LEVEL,
                           p_max=DEFAULT_P_ADVERSE_MAX, min_evidence=DEFAULT_MIN_EVIDENCE,
                           credible_mass=0.90):
    """Run both safe-set update rules over the same sequence of classifications and compare.

    ``X_sequence`` is a list of candidate arrays, one per update, all on the same rows. In the
    intended use every entry is the same grid and the model has been refitted between calls;
    passing the grid repeatedly with a single fitted model reproduces the degenerate case in
    which the two rules must agree, which is a useful check on the implementation.

    Returns the size of each set after every update and the cells the two rules disagree about
    at the end, which is the comparison worth reading: it is the set of cells the cumulative rule
    is still calling safe after the model stopped doing so.
    """
    rec = SafeSetTracker(mode="recomputed")
    cum = SafeSetTracker(mode="cumulative")
    history = []
    last = None
    for X in X_sequence:
        c = model.classify(X, level=level, p_max=p_max, min_evidence=min_evidence,
                           credible_mass=credible_mass)
        m_rec = rec.update(c["label"])
        m_cum = cum.update(c["label"], c["n_eff"], min_evidence=min_evidence)
        history.append({"n_recomputed": int(m_rec.sum()), "n_cumulative": int(m_cum.sum())})
        last = (X, m_rec, m_cum)
    X, m_rec, m_cum = last
    only_cum = m_cum & ~m_rec
    return {
        "history": history,
        "n_recomputed_final": int(m_rec.sum()),
        "n_cumulative_final": int(m_cum.sum()),
        "n_only_in_cumulative": int(only_cum.sum()),
        "cells_only_in_cumulative": X[only_cum].tolist(),
        "contiguity_violations_recomputed":
            SafeSetTracker.contiguity_violations(m_rec, X),
        "contiguity_violations_cumulative":
            SafeSetTracker.contiguity_violations(m_cum, X),
    }
