# Generated by Django 5.1.3 on 2025-02-15 15:55

import Server.models.User
import django.db.models.deletion
import modules.HelperFunctions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensing_type', models.CharField(default='Unknown', max_length=128)),
                ('sensing', models.JSONField(default=dict)),
                ('adaptive_type', models.CharField(default='Unknown', max_length=128)),
                ('adaptive', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('metadata', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalStimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.JSONField(default=list)),
                ('return_contact', models.JSONField(default=list)),
                ('amplitude', models.FloatField(default=0)),
                ('amplitude_fraction', models.JSONField(default=list)),
                ('amplitude_unit', models.CharField(default='mA', max_length=128)),
                ('pulsewidth', models.FloatField(default=90)),
                ('pulsewidth_unit', models.CharField(default='uS', max_length=128)),
                ('frequency', models.FloatField(default=125)),
                ('cycling', models.FloatField(default=1)),
                ('cycling_period', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Electrode',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(default='', max_length=128)),
                ('name', models.CharField(default='', max_length=128)),
                ('hemisphere', models.CharField(default='', max_length=128)),
                ('target', models.CharField(default='', max_length=128)),
                ('custom_name', models.CharField(default='', max_length=128)),
                ('channel_count', models.IntegerField(default=4)),
                ('channel_names', models.JSONField(default=list)),
                ('channel_mapping', models.CharField(default='', max_length=512)),
                ('channel_coordinates', models.JSONField(default=list)),
                ('implanted_date', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('invite_code', models.CharField(default='', max_length=512)),
                ('name', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=512)),
                ('invite_code', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(default='', max_length=128)),
                ('group_name', models.CharField(default='', max_length=128)),
                ('group_id', models.CharField(default='', max_length=128)),
                ('stimulation_type', models.CharField(default='', max_length=128)),
                ('adaptive_settings', models.ManyToManyField(related_name='has_adaptive', to='Server.adaptivetherapy')),
                ('stimulation_settings', models.ManyToManyField(related_name='has_setting', to='Server.electricalstimulation')),
            ],
        ),
        migrations.AddField(
            model_name='electricalstimulation',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.electricaltherapy'),
        ),
        migrations.AddField(
            model_name='adaptivetherapy',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.electricaltherapy'),
        ),
        migrations.AddField(
            model_name='electricalstimulation',
            name='electrode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.electrode'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=512)),
                ('date_of_birth', models.FloatField(default=0)),
                ('sex', models.CharField(default='Unknown', max_length=32)),
                ('mrn', models.CharField(default='', max_length=128)),
                ('diagnosis', models.CharField(default='Unknown', max_length=128)),
                ('disease_start_time', models.FloatField(default=0)),
                ('last_update', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.institute')),
                ('original', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
                ('tags', models.ManyToManyField(related_name='has_tag', to='Server.tag')),
            ],
        ),
        migrations.CreateModel(
            name='MERDevice',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('electrodes', models.ManyToManyField(related_name='has_mer_electrode', to='Server.electrode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
            ],
        ),
        migrations.CreateModel(
            name='FitbitDevice',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('pkce', models.CharField(default=modules.HelperFunctions.PKCE_code_verifier, max_length=128)),
                ('auth', models.JSONField(default=dict)),
                ('date_periods', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
            ],
        ),
        migrations.AddField(
            model_name='electrode',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant'),
        ),
        migrations.CreateModel(
            name='DBSDevice',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('serial_number', models.CharField(default='', max_length=256)),
                ('implanted_location', models.CharField(default='', max_length=128)),
                ('implanted_date', models.FloatField(default=0)),
                ('estimated_eol', models.FloatField(default=0)),
                ('device_bloodline', models.CharField(default='', max_length=128)),
                ('electrodes', models.ManyToManyField(related_name='has_dbs_electrode', to='Server.electrode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('adjusted_alignment', models.FloatField(default=0)),
                ('pointer', models.CharField(default='', max_length=1024)),
                ('hashed', models.CharField(default='', max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('original', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.recording')),
            ],
        ),
        migrations.CreateModel(
            name='RecordingRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_shift', models.FloatField(default=0)),
                ('data_type', models.CharField(default='', max_length=128)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.analysis')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.recording')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='recordings',
            field=models.ManyToManyField(through='Server.RecordingRel', to='Server.recording'),
        ),
        migrations.CreateModel(
            name='ScaleForms',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('short_link', models.CharField(default=modules.HelperFunctions.get_token, max_length=128)),
                ('record', models.JSONField(default=list)),
                ('record_type', models.CharField(default='', max_length=128)),
                ('record_version', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.institute')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantLinkRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_code', models.CharField(default='', max_length=128)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.scaleforms')),
            ],
        ),
        migrations.CreateModel(
            name='ScaleRecord',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('record', models.JSONField(default=dict)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.scaleforms')),
            ],
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=512)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('pointer', models.CharField(default='', max_length=1024)),
                ('hashed', models.CharField(default='', max_length=64)),
                ('metadata', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.sourcefile'),
        ),
        migrations.CreateModel(
            name='DBSEvent',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('data', models.ManyToManyField(related_name='has_data', to='Server.recording')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('duration', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='StudyDataRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.JSONField(default=dict)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.study')),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='participants',
            field=models.ManyToManyField(related_name='has_participant', through='Server.StudyDataRel', to='Server.participant'),
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(default='', max_length=128)),
                ('dosage', models.FloatField(default=0)),
                ('dosage_unit', models.CharField(default='', max_length=128)),
                ('frequency', models.CharField(default='', max_length=128)),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.therapy')),
            ],
        ),
        migrations.AddField(
            model_name='electricaltherapy',
            name='therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.therapy'),
        ),
        migrations.CreateModel(
            name='TherapyModification',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('previous_state', models.CharField(default='', max_length=128)),
                ('new_state', models.CharField(default='', max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.sourcefile')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('user_name', models.CharField(default='', max_length=255)),
                ('register_date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('configuration', models.JSONField(default=dict)),
                ('api_token', models.CharField(default=Server.models.User.newToken, max_length=128)),
                ('verification_code', models.CharField(default=Server.models.User.newVerification, max_length=16)),
                ('is_active', models.IntegerField(default=1)),
                ('is_mobile', models.IntegerField(default=0)),
                ('is_admin', models.IntegerField(default=0)),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Server.institute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudyRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.JSONField(default=dict)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.study')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='members',
            field=models.ManyToManyField(related_name='study_has_member', through='Server.StudyRel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InstituteRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.JSONField(default=dict)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.institute')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='members',
            field=models.ManyToManyField(related_name='institute_has_member', through='Server.InstituteRel', to=settings.AUTH_USER_MODEL),
        ),
    ]
