# Generated by Django 5.1.3 on 2025-01-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedrecording',
            name='adjusted_alignment',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='adjusted_alignment',
            field=models.FloatField(default=0),
        ),
    ]
