# Generated by Django 5.1.6 on 2025-06-11 15:09

import modules.HelperFunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistRecords',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=512)),
                ('ip_address', models.CharField(default='', max_length=32)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('reason', models.CharField(default='', max_length=512)),
            ],
        ),
    ]
