# Generated by Django 5.1.6 on 2025-07-08 20:18

import django.db.models.deletion
import modules.HelperFunctions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_blacklistrecords'),
    ]

    operations = [
        migrations.CreateModel(
            name='OuraRingDevice',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=128)),
                ('type', models.CharField(default='', max_length=128)),
                ('pkce', models.CharField(default=modules.HelperFunctions.PKCE_code_verifier, max_length=128)),
                ('auth', models.JSONField(default=dict)),
                ('date_periods', models.JSONField(default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.participant')),
            ],
        ),
    ]
