# Generated by Django 5.1.3 on 2025-01-12 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_processedrecording_adjusted_alignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Server.recording'),
        ),
        migrations.DeleteModel(
            name='ProcessedRecording',
        ),
    ]
