# Generated by Django 5.1.3 on 2025-09-08 15:35

import django.db.models.deletion
import modules.HelperFunctions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_ouraringdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncJob',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=512)),
                ('type', models.CharField(default='', max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('metadata', models.JSONField(default=dict)),
                ('recording_uid', models.CharField(blank=True, default='', max_length=32)),
                ('state', models.CharField(default='Pending', max_length=32)),
                ('result_message', models.CharField(blank=True, default='', max_length=1024)),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
