# Generated by Django 5.1.3 on 2025-10-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0004_asyncjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricaltherapy',
            name='label',
            field=models.CharField(default='', max_length=128),
        ),
    ]
