# Generated by Django 5.1.3 on 2025-12-22 16:42

import Server.models.User
import django.db.models.deletion
import modules.HelperFunctions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0005_electricaltherapy_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationTokens',
            fields=[
                ('uid', models.CharField(default=modules.HelperFunctions.uuid4_hex, max_length=32, primary_key=True, serialize=False)),
                ('type', models.CharField(default='Desktop', max_length=128)),
                ('token', models.CharField(default=Server.models.User.newToken, max_length=128)),
                ('date', models.FloatField(default=modules.HelperFunctions.current_time)),
                ('ip_address', models.CharField(default='', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
