# Generated by Django 4.0.6 on 2024-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_combinedrecordinganalysis_analysis_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='perceptsession',
            name='session_timezone',
            field=models.CharField(default='', max_length=255),
        ),
    ]
