# Generated by Django 4.0.6 on 2024-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0011_perceptsession_session_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralactivityrecording',
            name='recording_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
