# Generated by Django 4.0.6 on 2024-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0012_alter_neuralactivityrecording_recording_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrecording',
            name='recording_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
