# Generated by Django 4.0.6 on 2024-11-07 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0013_alter_externalrecording_recording_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveMarkerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deidentified_id', models.UUIDField(default=uuid.uuid4)),
                ('recording_id', models.UUIDField(default=uuid.uuid4)),
                ('recording_channel', models.CharField(default='', max_length=64)),
                ('therapy_overview', models.CharField(default='', max_length=128)),
                ('objective_marker', models.CharField(default='', max_length=64)),
                ('source_file', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
